Repository finos/legend-sdlc, pull requests merged in 2022-10, with the labels that each got.

#527 Uptick engine version
  pom.xml
Labels: cla-present

#529 Fix exception handling in TestModelBuilder
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/test/TestModelBuilder.java
Labels: cla-present

#531 add `sessionCookie` to test and Docker config to help with development using docker-compose
  legend-sdlc-server/src/main/resources/docker/config/config.json
  legend-sdlc-server/src/test/resources/config-test.yaml
Labels: cla-present

#532 unignore test failure in PR CIs
  .github/workflows/build.yml
Labels: cla-present

#516 adding support for mapping testables
  legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/pure/v1/MappingTestCase.java
  legend-sdlc-test-utils/src/test/java/org/finos/legend/sdlc/test/junit/TestLegendSDLCTestSuiteBuilder.java
  legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-mapping-with-testTestSuites/entities/data/RelationalData.json
  legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-mapping-with-testTestSuites/entities/execution/RelationalMapping.json
  legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-mapping-with-testTestSuites/entities/model/Firm.json
  legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-mapping-with-testTestSuites/entities/model/Person.json
  legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-mapping-with-testTestSuites/entities/store/TestDB.json
  pom.xml
Labels: enhancement, cla-present, depends on engine

#526 A comprehensive error handling strategy of pulling entities -- part I
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/entity/EntityAccessContext.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabEntityApi.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/BackupWorkspaceEntitiesResource.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/BackupWorkspaceRevisionEntitiesResource.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ComparisonReviewEntitiesResource.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ConflictResolutionWorkspaceEntitiesResource.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ConflictResolutionWorkspaceRevisionEntitiesResource.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/EntityAccessResource.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/GroupBackupWorkspaceEntitiesResource.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/GroupBackupWorkspaceRevisionEntitiesResource.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/GroupConflictResolutionWorkspaceEntitiesResource.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/GroupConflictResolutionWorkspaceRevisionEntitiesResource.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/GroupWorkspaceEntitiesResource.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/GroupWorkspaceRevisionEntitiesResource.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ProjectEntitiesResource.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ProjectRevisionEntitiesResource.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/VersionEntitiesResource.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/WorkspaceEntitiesResource.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/WorkspaceRevisionEntitiesResource.java
  legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/api/InMemoryEntityApi.java
Labels: enhancement, cla-present

#535 Update engine version
  pom.xml
Labels: cla-present

#538 Update CODEOWNERS
  CODEOWNERS
Labels: cla-present

#542 Bump apache commons text from 1.8 to 1.10.0
  pom.xml
Labels: cla-present

#539 Load extensions using ServiceLoader for tests
  legend-sdlc-generation-service/pom.xml
  legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionGenerator.java
Labels: cla-present

#545 update legend engine version to 3.19.4
  pom.xml
Labels: cla-present

#537 Add /reviews/{reviewId}/approval API
  legend-sdlc-model/src/main/java/org/finos/legend/sdlc/domain/model/review/Approval.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/review/ReviewApi.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/BaseGitLabApi.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabReviewApi.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ReviewsResource.java
  legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/api/InMemoryReviewApi.java
Labels: cla-present

#515 support function overloading
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/BaseGitLabApi.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabEntityApi.java
  legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/TestBaseGitLabApi.java
Labels: cla-present, depends on engine

#546 Update legend engine version to 3.20.1
  pom.xml
Labels: cla-present

#549 Upgrade Engine to 3.21.0
  pom.xml
Labels: cla-present

#548 Upgrade snakeyaml version to 1.33
  pom.xml
Labels: cla-present

#550 support function overloading (minor test fix)
  legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/EntityValidator.java
  pom.xml
Labels: cla-present

#551 support function overloading minor fix
  legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/EntityValidator.java
Labels: bug, cla-present

#552 bump engine 3.21.0
  pom.xml
Labels: cla-present

#553 Move entity path validation to legend-sdlc-model
  legend-sdlc-model/src/main/java/org/finos/legend/sdlc/tools/entity/EntityPaths.java
  legend-sdlc-model/src/test/java/org/finos/legend/sdlc/tools/entity/TestEntityPaths.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/BaseGitLabApi.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabEntityApi.java
  legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabRevisionApi.java
  legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/EntityValidator.java
Labels: enhancement, cla-present
